### ISSUE TITLE
Support async via https://github.com/aantron/promise

### ISSUE THREAD

**Issue by fakenickels** [sikanhe/reason-graphql#39]
Also opening as a suggestion for discussing this matter

**Comment by leeor** [comment]
Actually, this is already supported through one of the schema variations, but I'm about to remove it. I'm removing it to reduce the dependency footprint, and since I think libraries should be agnostic to these sort of frameworks. Functors provide an easy mechanism for specialising a library to the specific code base it is used in.

Have a look at #37.

**Comment by sikanhe** [comment]
This should be possible!
